### ISSUE TITLE
Deployment to Azure Cloud and Running Angular App

### ISSUE THREAD

**Issue by RealMosam** [HARSHINIGOSU/SportsEventManagementSystem#1]
Hi, I wanted to know how to deploy theses services to azure. And also how to run Angular front-end because until the Micro-services are running on the local host, the Angular App doesn't fetch data from the databases. Please provide brief steps about it. Thanks.

**Comment by HARSHINIGOSU** [comment]
Did u go through the Readme File??

**Comment by RealMosam** [comment]
Yes.

**Comment by RealMosam** [comment]
![Screenshot (419)](https://user-images.githubusercontent.com/36242921/183253535-1eeef4c4-a388-41d2-ba99-7558421b599c.png)
![Screenshot (420)](https://user-images.githubusercontent.com/36242921/183253539-ad419048-32aa-45ca-875d-743ab6e2f533.png)
As you can see the app is running but not fetching data, i.e., signing or signing up is not working.

**Comment by HARSHINIGOSU** [comment]
Did you insert the data in the table of sports,events in the Microsoft sql
server as per readme...
And to make the app work you should keep the swagger run and then run the
angular part

**Comment by RealMosam** [comment]
Yes everything works fine when I run the Swagger and then try to access the Databases using Angular Front-end. But as you see there are 4 Different micro-services and each of them have different databases, also I can't run them simultaneously that's why the Angular App is not able to fetch all the data at a time. Is there any way to run all the micro-services together on local host?

**Comment by HARSHINIGOSU** [comment]
U should run 4 microservices separately and then u have run the angular

**Comment by RealMosam** [comment]
Okay got it. I thought we can merge them into a single solution. Thanks. And the deployment part?

**Comment by HARSHINIGOSU** [comment]
Cool then... Actually we didn't deploy it but I think we have to deploy the
every microservice individually
